name: vcmi
version: '0.99+git'
summary: VCMI engine
description: |
  Open-source engine for Heroes of Might and Magic III
confinement: strict
grade: devel

apps:
  vcmilauncher:
    command: desktop-launch $SNAP/game/vcmilauncher
    desktop: game/share/applications/vcmilauncher.desktop
    plugs:
      - unity7
      - network
      - network-manager
      - opengl
      - x11
    environment:
      LC_ALL: C.UTF-8
  vcmiclient:
    command: desktop-launch $SNAP/game/vcmiclient
    desktop: game/share/applications/vcmiclient.desktop
    plugs:
      - network
      - network-bind
      - opengl
      - pulseaudio
      - alsa
      - x11
    environment:
      LC_ALL: C.UTF-8
  vcmiserver:
    command: desktop-launch $SNAP/game/vcmiserver
    plugs:
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8

parts:
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libqt5core5a
      - libqt5gui5-gles
      - libqt5network5
      - libqt5widgets5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
  vcmi:
    plugin: cmake
    source: https://github.com/vcmi/vcmi.git
    configflags:
      - -DCMAKE_INSTALL_PREFIX:PATH=/game
      - -DENABLE_MONOLITHIC_INSTALL=ON
    after: [desktop-qt5]
    build-packages:
      - build-essential
      - cmake
      - cmake-data
      - cmake-extras
      - debhelper
      - dbus
      - libminizip-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - zlib1g-dev
      - libavformat-dev
      - libswscale-dev
      - libboost-dev
      - libboost-program-options-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libboost-locale-dev
      - libboost-thread-dev
      - libboost-test-dev
      - qtbase5-dev
      - pkg-config
      - protobuf-compiler
    stage-packages:
      - libavcodec-ffmpeg56
      - libavcodec-ffmpeg-extra56
      - libavformat-ffmpeg56
      - libavutil-ffmpeg54
      - libboost-date-time1.58.0
      - libboost-filesystem1.58.0
      - libboost-locale1.58.0
      - libboost-program-options1.58.0
      - libboost-system1.58.0
      - libboost-thread1.58.0
      - libc6
      - libgcc1
      - libminizip1
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libstdc++6
      - libswscale-ffmpeg3
      - zlib1g
